// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhgjztnauponaspmvjrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoZ2p6dG5hdXBvbmFzcG12anJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NjE5NTYsImV4cCI6MjA3MTQzNzk1Nn0.fxuTnrSJ8QJHU9DVY54fLy5pZyR0KEpQKP802bZrkFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});